# Generated by Django 6.0.6 on 2026-06-12 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calidad', models.CharField(choices=[('premium', 'Premium'), ('primera', 'Primera'), ('segunda', 'Segunda'), ('rechazada', 'Rechazada')], default='primera', max_length=20)),
                ('almacen', models.CharField(blank=True, max_length=80, null=True)),
                ('zona', models.CharField(blank=True, max_length=50, null=True)),
                ('estante', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('en_proceso', 'En proceso'), ('vendido', 'Vendido'), ('exportado', 'Exportado'), ('observado', 'Observado')], default='disponible', max_length=20)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='compras.compra')),
            ],
        ),
    ]
