# Generated by Django 6.0.6 on 2026-06-12 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('fecha_compra', models.DateField()),
                ('departamento', models.CharField(max_length=80)),
                ('provincia', models.CharField(max_length=80)),
                ('distrito', models.CharField(max_length=80)),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=80, null=True)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('programado', 'Programado'), ('pagado', 'Pagado'), ('fallido', 'Fallido'), ('anulado', 'Anulado')], default='pendiente', max_length=20)),
                ('estado_evaluacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_evaluacion', 'En evaluación'), ('evaluada', 'Evaluada'), ('observada', 'Observada')], default='pendiente', max_length=20)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='proveedores.proveedor')),
            ],
        ),
    ]
